const express = require('express');
const router = express.Router();
const multer = require('multer');
const { protect } = require('../middleware/auth');
const { predict, getScans, getStats, getDaywiseStats, getBatchwiseStats, deleteScan } = require('../controllers/scanController');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (req, file, cb) => { if (!file.mimetype.startsWith('image/')) return cb(new Error('Only image files are allowed'), false); cb(null, true); } });
router.post('/predict',        protect, upload.single('file'), predict);
router.get('/stats',           protect, getStats);
router.get('/stats/daywise',   protect, getDaywiseStats);
router.get('/stats/batchwise', protect, getBatchwiseStats);
router.get('/',                protect, getScans);
router.delete('/:id',          protect, deleteScan);
module.exports = router;
